# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ shiny_server_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - shiny-server-install-dependencies

- name: install | additional
  apt:
    name: "{{ shiny_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - shiny-server-install-additional

- name: install | create (download) directory
  file:
    path: "{{ shiny_server_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - shiny-server-install-download
    - shiny-server-install-download-directory

- name: install | download deb
  command: >
    curl -sSL
    https://download3.rstudio.org/ubuntu-14.04/{{ ansible_machine }}/shiny-server-{{ shiny_server_version }}-{{ shiny_server_machine_map[ansible_machine] }}.deb
    -o {{ shiny_server_downloads_path }}/shiny-server_{{ shiny_server_version }}_{{ shiny_server_machine_map[ansible_machine] }}.deb
  args:
    creates: "{{ shiny_server_downloads_path }}/shiny-server_{{ shiny_server_version }}_{{ shiny_server_machine_map[ansible_machine] }}.deb"
    warn: false
  tags:
    - shiny-server-install-download
    - shiny-server-install-download-deb

- name: install | install deb
  apt:
    deb: "{{ shiny_server_downloads_path }}/shiny-server_{{ shiny_server_version }}_{{ shiny_server_machine_map[ansible_machine] }}.deb"
  tags:
    - shiny-server-install-install
    - shiny-server-install-install-deb
